apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mymongodb
spec:
  serviceName: mymongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mymongodb
  template:
    metadata:
      labels:
        app: mymongodb
    spec:
      containers:
        - name: mymongodb
          image: mongo:3
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mymongodb_data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-config
                  key: MONGO_PASSWORD
      envFrom:
        - configMapRef:
            name: mongo-config.properties
  volumeClaimTemplates:
    - metadata:
        name: mymongodb_data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mymongodb-service
spec:
  selector:
    app: mymongodb
  type: NodePort
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_CONTAINER: mymongodb
  MONGO_HOST: mymongodb
  MONGO_PORT: 27017
  MONGO_DB: dbinventory
  MONGO_USERNAME: user
  MONGO_PASSWORD: pass
  MONGO_AUTHUSER: admin





